# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_perlin', [dirname(__file__)])
        except ImportError:
            import _perlin
            return _perlin
        if fp is not None:
            try:
                _mod = imp.load_module('_perlin', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _perlin = swig_import_helper()
    del swig_import_helper
else:
    import _perlin
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


B = _perlin.B
BM = _perlin.BM
N = _perlin.N
NP = _perlin.NP
NM = _perlin.NM

def init():
  return _perlin.init()
init = _perlin.init

def noise1(*args):
  return _perlin.noise1(*args)
noise1 = _perlin.noise1

def noise2(*args):
  return _perlin.noise2(*args)
noise2 = _perlin.noise2

def noise3(*args):
  return _perlin.noise3(*args)
noise3 = _perlin.noise3

def normalize3(*args):
  return _perlin.normalize3(*args)
normalize3 = _perlin.normalize3

def normalize2(*args):
  return _perlin.normalize2(*args)
normalize2 = _perlin.normalize2

def PerlinNoise1D(*args):
  return _perlin.PerlinNoise1D(*args)
PerlinNoise1D = _perlin.PerlinNoise1D

def PerlinNoise2D(*args):
  return _perlin.PerlinNoise2D(*args)
PerlinNoise2D = _perlin.PerlinNoise2D

def PerlinNoise3D(*args):
  return _perlin.PerlinNoise3D(*args)
PerlinNoise3D = _perlin.PerlinNoise3D


